#!/bin/bash
#SBATCH --job-name=sgr_euc_norm
#SBATCH --time=08:00:00            
#SBATCH --partition=gpu_h100       # Note: Using gpu_h100 as per your teammate's script
#SBATCH --gpus=1                   
#SBATCH --cpus-per-task=9          
#SBATCH --array=1-270              # 270 tasks generated by the script above
#SBATCH --output=/scratch-shared/%u/output/sgr/euclidean/norm_array_%A_%a.out 
#SBATCH --error=/scratch-shared/%u/logs/sgr/euclidean/norm_array_%A_%a.err  

set -euo pipefail

# 1. Environment loading
module purge
module load 2025
module load Anaconda3/2025.06-1

source "$(conda info --base)/etc/profile.d/conda.sh"
set +u
conda activate base
conda install -y -n manifm -c conda-forge libstdcxx-ng libgcc-ng
conda activate manifm
set -u

cd "$HOME/DL2_project/Spherical-Flow-Matching/riemannian-fm"
export WANDB_CACHE_DIR="/scratch-shared/$USER/wandb-cache"

# 2. Correctly create nested directories
mkdir -p "$WANDB_CACHE_DIR"
mkdir -p /scratch-shared/$USER/logs/sgr/euclidean 
mkdir -p /scratch-shared/$USER/output/sgr/euclidean 
mkdir -p /scratch-shared/$USER/failed_tasks/sgr/euclidean

TASKS_FILE="tasks/sgr_euclidean_norm.txt"

# 3. Extract the command corresponding to the current task ID
COMMAND=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "$TASKS_FILE")

echo "Starting Task ID: $SLURM_ARRAY_TASK_ID"
echo "Command: $COMMAND"
echo "--------------------------------------------------------"

# 4. Execute the command. stdout and stderr are automatically routed by Slurm
eval "$COMMAND"
EXIT_CODE=$?

# 5. Corrected failure logic mapping exactly to the #SBATCH output/error paths
if [ $EXIT_CODE -ne 0 ]; then
    echo "Task $SLURM_ARRAY_TASK_ID failed with exit code $EXIT_CODE."
    
    cp "/scratch-shared/$USER/output/sgr/euclidean/norm_array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out" /scratch-shared/$USER/failed_tasks/sgr/euclidean/
    cp "/scratch-shared/$USER/logs/sgr/euclidean/norm_array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err" /scratch-shared/$USER/failed_tasks/sgr/euclidean/
    
    echo "Logs copied to failed_tasks/sgr/euclidean/ directory."
fi

exit $EXIT_CODE